import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image'
import prof from '../imgs/Gallupprof.jpg'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="home-container">
        <Image className='circle-image' src={prof} alt="Picture of the author" width={300} height={300} />
        <div className="greeting">
          <h1>Hi, I'm Dakota</h1>
          <h2>Software Developer</h2>
        </div>
        <div className='about'>
          <h3>About</h3>
          <h4>
            I am recent graduate of University of South Dakota
            where I studied Computer Science, Mathematics, and 
            Artificial Intelligence. Now, I am currently a Software
            Developer at Gallup, Inc. in Omaha, NE.
          </h4>
        </div>
      </div>
    </>
  )
}
